'use strict';
const width = 12;
const height = 32;
const area = width * height;
console.log('area:', area);
console.log('Type of area:', typeof area);
const bill = 27;
const payment = 30;
const change = payment - bill;
console.log('change:', change);
console.log('Type of change:', typeof change);
const quizzes = 76;
const midterm = 67;
const final = 58;
const grade = (quizzes + midterm + final) / 3;
console.log('grade:', grade);
console.log('Type of grade:', typeof grade);
const firstName = 'Ebenezer';
const lastName = 'Scrooge';
const fullName = firstName + ' ' + lastName;
console.log('fullName:', fullName);
console.log('Type of fullName:', typeof fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log('isAcidic:', isAcidic);
console.log('Type of isAcidic:', typeof isAcidic);
const headCount = 200;
const isSparta = headCount === 300;
console.log('isSparta:', isSparta);
console.log('Type of isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is a humbug!';
console.log('motto:', motto);
console.log('Type of motto:', typeof motto);
